apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  creationTimestamp: null
  name: azure
  namespace: openshift-cluster-api
spec:
  deployment:
    containers:
    - command:
      - ./bin/cluster-api-provider-azure-controller-manager
      name: manager
  fetchConfig:
    selector:
      matchLabels:
        provider.cluster.x-k8s.io/name: azure
        provider.cluster.x-k8s.io/type: infrastructure
  version: v1.7.1
status: {}
