// Code generated by "stringer -type=Reason -trimprefix=Reason"; DO NOT EDIT.

package operatorstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReasonUnknown-0]
	_ = x[ReasonAsExpected-1]
	_ = x[ReasonUninitialized-2]
	_ = x[ReasonProgressing-3]
	_ = x[ReasonWaitingOnExternal-4]
	_ = x[ReasonEphemeralError-5]
	_ = x[ReasonNonRetryableError-6]
}

const _Reason_name = "UnknownAsExpectedUninitializedProgressingWaitingOnExternalEphemeralErrorNonRetryableError"

var _Reason_index = [...]uint8{0, 7, 17, 30, 41, 58, 72, 89}

func (i Reason) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Reason_index)-1 {
		return "Reason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Reason_name[_Reason_index[idx]:_Reason_index[idx+1]]
}
