run:
  timeout: "30m"

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Additional linters
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - err113
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - tagliatelle
    - usetesting
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
linters-settings:
  cyclop:
    max-complexity: 20
  goheader:
    values:
      regexp:
        license-year: (202[1-9]|20[3-9][0-9])
    template: |-
      Copyright {{license-year}} Red Hat, Inc.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

      	http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
  importas:
    alias:
      - pkg: "sigs.k8s.io/cluster-api/api/v1beta1"
        alias: "clusterv1"
      - pkg: "sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2"
        alias: "awsv1"
      - pkg: "sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta2"
        alias: "ibmpowervsv1"
    no-unaliased: true
  nlreturn:
    block-size: 2
  revive:
    confidence: 0
    rules:
    - name: exported
      severity: warning
      disabled: false
      arguments:
        - "checkPrivateReceivers"
        - "disableStutteringCheck"
  staticcheck:
    checks:
      # SA1019: Using a deprecated function, variable, constant or field
      #
      # We need to consider deprecated fields in MAPO-CAPO conversions
      - "-SA1019"
  stylecheck:
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1000"]
    dot-import-whitelist:
      - "github.com/onsi/ginkgo/v2"
      - "github.com/onsi/gomega"
issues:
  exclude:
    # Not all platforms are supported by this operator, those which aren't
    # supported will be caught by the default case in the switches.
    - "missing cases in switch of type v1.PlatformType: (\\.*)"
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go|pkg/test/*
      linters:
        - gocyclo
        - dupl
        - gosec
        - gochecknoglobals
        - err113
        - wrapcheck
