---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crd-compatibility-requirements
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apiextensions-k8s-io-v1-customresourcedefinition
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: crdcompatibility.operator.openshift.io
  rules:
  - apiGroups:
    - apiextensions.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - customresourcedefinitions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crd-compatibility-controller
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-openshift-io-v1alpha1-crdcompatibilityrequirement
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: crdcompatibility.operator.openshift.io
  rules:
  - apiGroups:
    - operator.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - crdcompatibilityrequirements
  sideEffects: None
