apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-capi-operator-images
  namespace: openshift-cluster-api
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    release.openshift.io/feature-gate: "TechPreviewNoUpgrade"
data:
  images.json: >
    {
      "cluster-capi-operator": "registry.ci.openshift.org/openshift:cluster-capi-operator",
      "cluster-kube-cluster-api-operator": "registry.ci.openshift.org/openshift:cluster-kube-cluster-api-operator",
      "cluster-capi-controllers": "registry.ci.openshift.org/openshift:cluster-capi-controllers",
      "aws-cluster-api-controllers": "registry.ci.openshift.org/openshift:aws-cluster-api-controllers",
      "kube-rbac-proxy": "registry.ci.openshift.org/openshift:kube-rbac-proxy"
    }
