apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-capi-operator:cluster-reader
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: "CustomNoUpgrade,TechPreviewNoUpgrade"
rules:
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
      - ipaddressclaims
      - ipaddresses
      - machinehealthchecks
      - machines
      - machinesets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - awsclusters
      - awsmachines
      - awsmachinetemplates
      - azuremachines
      - azuremachinetemplates
      - azureclusters
      - gcpclusters
      - gcpmachines
      - gcpmachinetemplates
    verbs:
      - get
      - list
      - watch
