---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: CustomNoUpgrade,TechPreviewNoUpgrade
  labels:
    provider.cluster.x-k8s.io/name: "openshift-cluster-api-aws"
    provider.cluster.x-k8s.io/type: "infrastructure"
    provider.cluster.x-k8s.io/version: "v4.21"
  name: cluster-api-aws-admission-policies
  namespace: openshift-cluster-api
data:
  # openshift admission policies specific to cluster-api aws
  components: |-
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingAdmissionPolicyBinding
    metadata:
      name: "openshift-cluster-api-unsupported-aws-spec-fields"
    spec:
      policyName: "openshift-cluster-api-unsupported-aws-spec-fields"
      validationActions: [Deny]
      matchResources:
        namespaceSelector:
          matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: In
            values:
            - openshift-cluster-api
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingAdmissionPolicy
    metadata:
      name: "openshift-cluster-api-unsupported-aws-spec-fields"
    spec:
      failurePolicy: Fail
      matchConstraints:
        resourceRules:
        - apiGroups:   ["infrastructure.cluster.x-k8s.io"]
          apiVersions: ["v1beta2"]
          operations:  ["CREATE", "UPDATE"]
          resources:   ["awsmachines", "awsmachinetemplates"]
      variables:
        - name: machineSpec
          expression: "object.kind == 'AWSMachine' ? object.spec : object.spec.template.spec"
      validations:
        - expression: "!has(variables.machineSpec.ami.eksLookupType)"
          message: "spec.ami.eksLookupType is a forbidden field"
        - expression: "!has(variables.machineSpec.imageLookupFormat)"
          message: "spec.imageLookupFormat is a forbidden field"
        - expression: "!has(variables.machineSpec.imageLookupOrg)"
          message: "spec.imageLookupOrg is a forbidden field"
        - expression: "!has(variables.machineSpec.imageLookupBaseOS)"
          message: "spec.imageLookupBaseOS is a forbidden field"
        - expression: "!has(variables.machineSpec.networkInterfaces)"
          message: "spec.networkInterfaces is a forbidden field"
        - expression: "!has(variables.machineSpec.uncompressedUserData)"
          message: "spec.uncompressedUserData is a forbidden field"
        - expression: "!has(variables.machineSpec.privateDnsName)"
          message: "spec.privateDnsName is a forbidden field"
        - expression: "!has(variables.machineSpec.ignition) || !has(variables.machineSpec.ignition.proxy)"
          message: "spec.ignition.proxy is a forbidden field"
        - expression: "!has(variables.machineSpec.ignition) || !has(variables.machineSpec.ignition.tls)"
          message: "spec.ignition.tls is a forbidden field"
        - expression: "!has(variables.machineSpec.securityGroupOverrides)"
          message: "spec.securityGroupOverrides is a forbidden field"
        - expression: >-
            !has(variables.machineSpec.cloudInit) || 
            (
             !has(variables.machineSpec.cloudInit.secretCount) &&
             !has(variables.machineSpec.cloudInit.secretPrefix) &&
             !has(variables.machineSpec.cloudInit.insecureSkipSecretsManager) &&
             !has(variables.machineSpec.cloudInit.secureSecretsBackend)
            )
          message: "spec.cloudInit is a forbidden field"
