# Tombstones for objects removed from the current Cluster API payload.
---
apiVersion: v1
kind: Secret
metadata:
  name: capi-controllers-token
  namespace: openshift-cluster-api
  annotations:
    release.openshift.io/delete: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "ClusterAPIMachineManagement"
    capability.openshift.io/name: ClusterAPI
