---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:capi-installer
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "ClusterAPIMachineManagement"
    capability.openshift.io/name: ClusterAPI
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-capi-installer
subjects:
- kind: ServiceAccount
  name: capi-installer
  namespace: openshift-cluster-api-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-installer
  namespace: openshift-cluster-api-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "ClusterAPIMachineManagement"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-installer
subjects:
- kind: ServiceAccount
  name: capi-installer
  namespace: openshift-cluster-api-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-installer
  namespace: openshift-cluster-api
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "ClusterAPIMachineManagement"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-installer
subjects:
- kind: ServiceAccount
  name: capi-installer
  namespace: openshift-cluster-api-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-installer
  namespace: openshift-machine-api
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "ClusterAPIMachineManagement"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-installer
subjects:
- kind: ServiceAccount
  name: capi-installer
  namespace: openshift-cluster-api-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:capi-installer-read-tls-configuration
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "ClusterAPIMachineManagement"
roleRef:
  kind: ClusterRole
  name: system:openshift:openshift-cluster-api:read-tls-configuration
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-api-operator
  name: capi-installer
