/*
Copyright 2025 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package crdcompatibility

import (
	"context"
	"fmt"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/controller-runtime/pkg/client"

	apiextensionsv1alpha1 "github.com/openshift/api/apiextensions/v1alpha1"
	"github.com/openshift/cluster-capi-operator/pkg/controllers/crdcompatibility/crdvalidation"
	"github.com/openshift/cluster-capi-operator/pkg/controllers/crdcompatibility/objectpruning"
	"github.com/openshift/cluster-capi-operator/pkg/controllers/crdcompatibility/objectvalidation"
	"github.com/openshift/cluster-capi-operator/pkg/test"
)

var defaultNodeTimeout = NodeTimeout(10 * time.Second)

func waitForReconcileComplete(ctx context.Context, requirement *apiextensionsv1alpha1.CompatibilityRequirement) {
	GinkgoHelper()

	By("Waiting for CompatibilityRequirement reconciliation to complete", func() {
		Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(HaveField("Status.Conditions", SatisfyAll(
			test.HaveCondition("Progressing").
				WithStatus(metav1.ConditionFalse).
				WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason).
				WithObservedGeneration(requirement.GetGeneration()),
		)))
	})
}

var _ = Describe("CompatibilityRequirement", Ordered, ContinueOnFailure, func() {
	// Starting and stopping the manager is quite expensive, so we share one amongst all the tests.
	// Unfortunately ginkgo forces us to use Ordered when doing this.
	BeforeAll(func(ctx context.Context) {
		_, startManager := InitManager(ctx)

		startManager()
	})

	var (
		// testCRDClean is a CRD generated by generateTestCRD.
		testCRDClean, testCRDWorking *apiextensionsv1.CustomResourceDefinition
	)

	BeforeEach(func() {
		testCRDClean = test.GenerateTestCRD()
	})

	Context("When creating a CompatibilityRequirement", func() {
		var testCRDWorking *apiextensionsv1.CustomResourceDefinition

		BeforeEach(func(ctx context.Context) {
			testCRDWorking = testCRDClean.DeepCopy()
			createTestObject(ctx, testCRDWorking, "CRD")
		}, defaultNodeTimeout)

		It("Should set all conditions and observed CRD", func(ctx context.Context) {
			requirement := test.GenerateTestCompatibilityRequirement(testCRDClean)
			createTestObject(ctx, requirement, "CompatibilityRequirement")

			By("Waiting for the CompatibilityRequirement to have the expected status")
			Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(SatisfyAll(
				HaveField("Status.Conditions", SatisfyAll(
					test.HaveCondition("Progressing").
						WithStatus(metav1.ConditionFalse).
						WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason).
						WithMessage("The CompatibilityRequirement is up to date"),
					test.HaveCondition("Admitted").
						WithStatus(metav1.ConditionTrue).
						WithReason(apiextensionsv1alpha1.CompatibilityRequirementAdmittedReason).
						WithMessage("The CompatibilityRequirement has been admitted"),
					test.HaveCondition("Compatible").
						WithStatus(metav1.ConditionTrue).
						WithReason(apiextensionsv1alpha1.CompatibilityRequirementCompatibleReason).
						WithMessage("The CRD is compatible with this requirement"),
				)),
				HaveField("Status.ObservedCRD.UID", BeEquivalentTo(testCRDWorking.UID)),
				HaveField("Status.ObservedCRD.Generation", BeEquivalentTo(testCRDWorking.Generation)),
			))
		}, defaultNodeTimeout)

		It("Should correctly update observed generation on conditions", func(ctx context.Context) {
			requirement := test.GenerateTestCompatibilityRequirement(testCRDClean)
			createTestObject(ctx, requirement, "CompatibilityRequirement")

			generation := requirement.GetGeneration()
			checkForStatusWithGeneration := func(generation int64) {
				Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(
					HaveField("Status.Conditions", SatisfyAll(
						test.HaveCondition("Progressing").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason).
							WithMessage("The CompatibilityRequirement is up to date").
							WithObservedGeneration(generation),
						test.HaveCondition("Admitted").
							WithStatus(metav1.ConditionTrue).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementAdmittedReason).
							WithMessage("The CompatibilityRequirement has been admitted").
							WithObservedGeneration(generation),
						test.HaveCondition("Compatible").
							WithStatus(metav1.ConditionTrue).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementCompatibleReason).
							WithMessage("The CRD is compatible with this requirement").
							WithObservedGeneration(generation),
					)),
				)
			}

			By("Waiting for the CompatibilityRequirement to have the expected status with observed generation 1")
			checkForStatusWithGeneration(generation)

			// Update the requirement to bump the generation
			Eventually(kWithCtx(ctx).Update(requirement, func() {
				requirement.Spec.CustomResourceDefinitionSchemaValidation.Action = apiextensionsv1alpha1.CRDAdmitActionWarn
			})).WithContext(ctx).Should(Succeed())

			// Sanity check that the generation has been bumped
			Expect(requirement).To(HaveField("ObjectMeta.Generation", BeNumerically(">", generation)))
			generation = requirement.GetGeneration()

			By("Waiting for the CompatibilityRequirement to have the expected status with observed generation 2")
			checkForStatusWithGeneration(generation)
		}, defaultNodeTimeout)

		It("Should not admit a CompatibilityRequirement if the CompatibilitySchema.CRDYAML does not parse", func(ctx context.Context) {
			requirement := test.GenerateTestCompatibilityRequirement(testCRDClean)
			requirement.Spec.CompatibilitySchema.CustomResourceDefinition.Data = "not YAML"

			By("Attempting to create invalid CompatibilityRequirement " + requirement.Name)

			expectedError := "admission webhook \"compatibilityrequirement.operator.openshift.io\" denied the request: spec.compatibilitySchema.customResourceDefinition.data: Invalid value: \"not YAML\": expected a valid CustomResourceDefinition in YAML format: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.CustomResourceDefinition"
			Eventually(tryCreate(ctx, requirement)).WithContext(ctx).Should(MatchError(expectedError))
		}, defaultNodeTimeout)

		It("Should not admit a CompatibilityRequirement if the CompatibilitySchema.CRDYAML parses but is not a CRD", func(ctx context.Context) {
			requirement := test.GenerateTestCompatibilityRequirement(testCRDClean)
			requirement.Spec.CompatibilitySchema.CustomResourceDefinition.Data = "{}"

			By("Attempting to create invalid CompatibilityRequirement " + requirement.Name)

			expectedError := "admission webhook \"compatibilityrequirement.operator.openshift.io\" denied the request: spec.compatibilitySchema.customResourceDefinition.data: Invalid value: \"\": expected a valid CustomResourceDefinition in YAML format: expected APIVersion to be apiextensions.k8s.io/v1 and Kind to be CustomResourceDefinition, got /"
			Eventually(tryCreate(ctx, requirement)).WithContext(ctx).Should(MatchError(expectedError))
		}, defaultNodeTimeout)

		It("Should not set an error when the CRD is not found", func(ctx context.Context) {
			differentCRD := test.GenerateTestCRD()
			requirement := test.GenerateTestCompatibilityRequirement(differentCRD)

			createTestObject(ctx, requirement, "CompatibilityRequirement")

			By("Waiting for the CompatibilityRequirement to have the expected status")
			Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(SatisfyAll(
				HaveField("Status.Conditions", test.HaveCondition("Progressing").
					WithStatus(metav1.ConditionFalse).
					WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason).
					WithMessage("The CompatibilityRequirement is up to date")),

				// observed CRD should be empty
				HaveField("Status.ObservedCRD.UID", BeZero()),
				HaveField("Status.ObservedCRD.Generation", BeZero()),
			))
		}, defaultNodeTimeout)

		Context("When creating a CompatibilityRequirement which is not compatible with the current CRD", func() {
			addProperty := func(crd *apiextensionsv1.CustomResourceDefinition, prop string) func() {
				return func() {
					crd.Spec.Versions[0].Schema.OpenAPIV3Schema.Properties[prop] = apiextensionsv1.JSONSchemaProps{
						Type: "string",
					}
				}
			}

			var (
				incompatibleCRD *apiextensionsv1.CustomResourceDefinition
				requirement     *apiextensionsv1alpha1.CompatibilityRequirement
			)

			BeforeEach(func(ctx context.Context) {
				// Create a compatibility CRD which requires an extra field
				incompatibleCRD = testCRDClean.DeepCopy()
				addProperty(incompatibleCRD, "extra")()

				By("Creating a new CompatibilityRequirement with a compatibility CRD which requires an extra field")

				requirement = test.GenerateTestCompatibilityRequirement(incompatibleCRD)
				createTestObject(ctx, requirement, "CompatibilityRequirement")
			}, defaultNodeTimeout)

			It("Should set not Compatible", func(ctx context.Context) {
				By("Checking that the CompatibilityRequirement is admitted but not compatible")
				Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(
					HaveField("Status.Conditions", SatisfyAll(
						test.HaveCondition("Progressing").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason),
						test.HaveCondition("Admitted").
							WithStatus(metav1.ConditionTrue).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementAdmittedReason),
						test.HaveCondition("Compatible").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementRequirementsNotMetReason),
					)),
				)
			}, defaultNodeTimeout)

			It("Should permit the CRD to be updated to be compatible", func(ctx context.Context) {
				By("Checking that the CompatibilityRequirement is not compatible")
				Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(
					HaveField("Status.Conditions", SatisfyAll(
						test.HaveCondition("Progressing").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason),
						test.HaveCondition("Compatible").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementRequirementsNotMetReason),
					)),
				)

				By("Updating the CRD to add the extra field")
				Eventually(kWithCtx(ctx).Update(testCRDWorking, addProperty(testCRDWorking, "extra"))).WithContext(ctx).Should(Succeed())

				By("Checking that the CompatibilityRequirement becomes compatible")
				Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(
					HaveField("Status.Conditions", SatisfyAll(
						test.HaveCondition("Progressing").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason),
						test.HaveCondition("Compatible").
							WithStatus(metav1.ConditionTrue).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementCompatibleReason),
					)),
				)
			}, defaultNodeTimeout)

			It("Should not permit the CRD to be updated if it would remain incompatible", func(ctx context.Context) {
				By("Checking that the CompatibilityRequirement is not compatible")
				Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(
					HaveField("Status.Conditions", SatisfyAll(
						test.HaveCondition("Progressing").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementUpToDateReason),
						test.HaveCondition("Compatible").
							WithStatus(metav1.ConditionFalse).
							WithReason(apiextensionsv1alpha1.CompatibilityRequirementRequirementsNotMetReason),
					)),
				)

				By("Attempt to update the CRD to add a different extra field")

				expectedError := "admission webhook \"compatibilityrequirement.operator.openshift.io\" denied the request: CRD is not compatible with CompatibilityRequirements: This requirement was added by CompatibilityRequirement " + requirement.Name + ": removed field : v1.^.extra"
				Eventually(kWithCtx(ctx).Update(testCRDWorking, addProperty(testCRDWorking, "extra2"))).WithContext(ctx).Should(MatchError(expectedError))
			}, defaultNodeTimeout)
		})
	})

	Context("When creating a CompatibilityRequirement with configured object schema validation", Ordered, func() {
		var requirement *apiextensionsv1alpha1.CompatibilityRequirement

		BeforeEach(func(ctx context.Context) {
			requirement = test.GenerateTestCompatibilityRequirement(testCRDClean)
			requirement.Spec.ObjectSchemaValidation = apiextensionsv1alpha1.ObjectSchemaValidation{
				Action: apiextensionsv1alpha1.CRDAdmitActionDeny,
				NamespaceSelector: metav1.LabelSelector{
					MatchLabels: map[string]string{
						"test": "test",
					},
				},
				ObjectSelector: metav1.LabelSelector{
					MatchLabels: map[string]string{
						"test": "test",
					},
				},
				MatchConditions: []admissionregistrationv1.MatchCondition{
					{
						Name:       "test",
						Expression: "true",
					},
				},
			}

			createTestObject(ctx, requirement, "CompatibilityRequirement")
		})

		It("Should create a validating webhook configuration to implement the compatibility requirement", func(ctx context.Context) {
			validatingWebhookConfig := &admissionregistrationv1.ValidatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{
					Name: requirement.Name,
				},
			}

			// We leverage a function in the objectvalidation package to create the validating webhook configuration.
			// Smoke test here that the right name and service details are used, the full spec is tested with the objectvalidation package.
			Eventually(kWithCtx(ctx).Object(validatingWebhookConfig)).WithContext(ctx).Should(SatisfyAll(
				HaveField("ObjectMeta.Name", BeEquivalentTo(requirement.Name)),
				HaveField("ObjectMeta.OwnerReferences", ContainElement(SatisfyAll(
					HaveField("APIVersion", Equal("apiextensions.openshift.io/v1alpha1")),
					HaveField("Kind", Equal("CompatibilityRequirement")),
					HaveField("Name", Equal(requirement.Name)),
					HaveField("UID", Equal(requirement.UID)),
					HaveField("Controller", HaveValue(Equal(true))),
					HaveField("BlockOwnerDeletion", HaveValue(Equal(true))),
				))),
				HaveField("Webhooks", ConsistOf(SatisfyAll(
					HaveField("Name", BeEquivalentTo("compatibilityrequirement.operator.openshift.io")),
					HaveField("ClientConfig.Service.Name", BeEquivalentTo("compatibility-requirements-controllers-webhook-service")),
					HaveField("ClientConfig.Service.Namespace", BeEquivalentTo("openshift-compatibility-requirements-operator")),
				))),
			))
		}, defaultNodeTimeout)

		It("Should create a mutating webhook configuration to implement the compatibility requirement", func(ctx context.Context) {
			mutatingWebhookConfig := &admissionregistrationv1.MutatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{
					Name: requirement.Name,
				},
			}

			// We leverage a function in the objectpruning package to create the mutating webhook configuration.
			// Smoke test here that the right name and service details are used, the full spec is tested with the objectpruning package.
			Eventually(kWithCtx(ctx).Object(mutatingWebhookConfig)).WithContext(ctx).Should(SatisfyAll(
				HaveField("ObjectMeta.Name", BeEquivalentTo(requirement.Name)),
				HaveField("ObjectMeta.OwnerReferences", ContainElement(SatisfyAll(
					HaveField("APIVersion", Equal("apiextensions.openshift.io/v1alpha1")),
					HaveField("Kind", Equal("CompatibilityRequirement")),
					HaveField("Name", Equal(requirement.Name)),
					HaveField("UID", Equal(requirement.UID)),
					HaveField("Controller", HaveValue(Equal(true))),
					HaveField("BlockOwnerDeletion", HaveValue(Equal(true))),
				))),
				HaveField("Webhooks", ConsistOf(SatisfyAll(
					HaveField("Name", BeEquivalentTo("compatibilityrequirement.operator.openshift.io")),
					HaveField("ClientConfig.Service.Name", BeEquivalentTo("compatibility-requirements-controllers-webhook-service")),
					HaveField("ClientConfig.Service.Namespace", BeEquivalentTo("openshift-compatibility-requirements-operator")),
				))),
			))
		}, defaultNodeTimeout)

		It("Should delete the validating webhook configuration when the CompatibilityRequirement is deleted", func(ctx context.Context) {
			validatingWebhookConfig := &admissionregistrationv1.ValidatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{
					Name: requirement.Name,
				},
			}

			Expect(cl.Delete(ctx, requirement)).To(Succeed())
			Eventually(kWithCtx(ctx).Get(validatingWebhookConfig)).WithContext(ctx).Should(test.BeK8SNotFound())
		}, defaultNodeTimeout)

		It("Should delete the mutating webhook configuration when the CompatibilityRequirement is deleted", func(ctx context.Context) {
			mutatingWebhookConfig := &admissionregistrationv1.MutatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{
					Name: requirement.Name,
				},
			}

			// No need to delete as we are in an ordered context and the previous test removes the compatibility requirement.
			Eventually(kWithCtx(ctx).Get(mutatingWebhookConfig)).WithContext(ctx).Should(test.BeK8SNotFound())
		}, defaultNodeTimeout)

		It("Should only have webhook configurations when the compatibility requirement sets object schema validation", func(ctx context.Context) {
			Expect(requirement.Spec.ObjectSchemaValidation).ToNot(BeZero(), "Later test setup relies on this being non-zero")

			By("Creating a CompatibilityRequirement without object schema validation")

			requirementWithoutObjectSchemaValidation := test.GenerateTestCompatibilityRequirement(testCRDClean)
			requirementWithoutObjectSchemaValidation.Spec.ObjectSchemaValidation = (apiextensionsv1alpha1.ObjectSchemaValidation{})

			createTestObject(ctx, requirementWithoutObjectSchemaValidation, "CompatibilityRequirement")

			By(fmt.Sprintf("Compatibility requirement %s created", requirementWithoutObjectSchemaValidation.Name))

			// Check that the CompatibilityRequirement is admitted
			waitForReconcileComplete(ctx, requirementWithoutObjectSchemaValidation)
			Expect(kWithCtx(ctx).Object(requirementWithoutObjectSchemaValidation)()).To(HaveField("Status.Conditions", SatisfyAll(
				test.HaveCondition("Admitted").
					WithStatus(metav1.ConditionTrue).
					WithReason(apiextensionsv1alpha1.CompatibilityRequirementAdmittedReason).
					WithObservedGeneration(requirementWithoutObjectSchemaValidation.Generation),
			)))

			noObjectSchemaValidatingWebhook := &admissionregistrationv1.ValidatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{
					Name: requirementWithoutObjectSchemaValidation.Name,
				},
			}
			noObjectSchemaMutatingWebhook := &admissionregistrationv1.MutatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{
					Name: requirementWithoutObjectSchemaValidation.Name,
				},
			}

			By("Checking that the webhook configurations are not present")
			Expect(kWithCtx(ctx).Get(noObjectSchemaValidatingWebhook)()).To(MatchError(ContainSubstring("not found")))
			Expect(kWithCtx(ctx).Get(noObjectSchemaMutatingWebhook)()).To(MatchError(ContainSubstring("not found")))

			By("Adding object schema validation back to the CompatibilityRequirement")
			Eventually(kWithCtx(ctx).Update(requirementWithoutObjectSchemaValidation, func() {
				requirementWithoutObjectSchemaValidation.Spec.ObjectSchemaValidation = requirement.Spec.ObjectSchemaValidation
			})).WithContext(ctx).Should(Succeed())

			waitForReconcileComplete(ctx, requirementWithoutObjectSchemaValidation)

			By("Checking that the webhook configurations are now present")
			Expect(kWithCtx(ctx).Get(noObjectSchemaValidatingWebhook)()).To(Succeed(), "The validating webhook configuration should be created")
			Expect(kWithCtx(ctx).Get(noObjectSchemaMutatingWebhook)()).To(Succeed(), "The mutating webhook configuration should be created")

			By("Removing the object schema validation from the CompatibilityRequirement")
			Eventually(kWithCtx(ctx).Update(requirementWithoutObjectSchemaValidation, func() {
				requirementWithoutObjectSchemaValidation.Spec.ObjectSchemaValidation = (apiextensionsv1alpha1.ObjectSchemaValidation{})
			})).WithContext(ctx).Should(Succeed())

			waitForReconcileComplete(ctx, requirementWithoutObjectSchemaValidation)

			By("Checking that the webhook configurations are now removed")
			Expect(kWithCtx(ctx).Get(noObjectSchemaValidatingWebhook)()).To(MatchError(ContainSubstring("not found")))
			Expect(kWithCtx(ctx).Get(noObjectSchemaMutatingWebhook)()).To(MatchError(ContainSubstring("not found")))
		}, defaultNodeTimeout)
	})

	Context("When managing webhooks with ownership conflicts", func() {
		var (
			requirement *apiextensionsv1alpha1.CompatibilityRequirement
			manualVWC   *admissionregistrationv1.ValidatingWebhookConfiguration
			manualMWC   *admissionregistrationv1.MutatingWebhookConfiguration
		)

		BeforeEach(func(ctx context.Context) {
			testCRDWorking = testCRDClean.DeepCopy()
			createTestObject(ctx, testCRDWorking, "CRD")

			// Create a requirement with a fixed name for testing
			requirement = test.GenerateTestCompatibilityRequirement(testCRDClean)
			requirement.Name = "test-requirement-with-conflict"
			requirement.GenerateName = ""
			requirement.Spec.ObjectSchemaValidation.Action = apiextensionsv1alpha1.CRDAdmitActionDeny

			// Create webhook manually with different owner using factory functions
			fakeOwner := metav1.OwnerReference{
				APIVersion: "apiextensions.openshift.io/v1alpha1",
				Kind:       "CompatibilityRequirement",
				Name:       "different-owner",
				UID:        types.UID("fake-uid-12345"),
				Controller: ptr.To(true),
			}

			manualVWC = objectvalidation.ValidatingWebhookConfigurationFor(requirement, testCRDClean)
			manualVWC.OwnerReferences = []metav1.OwnerReference{fakeOwner}
			createTestObject(ctx, manualVWC, "Manual ValidatingWebhookConfiguration")

			manualMWC = objectpruning.MutatingWebhookConfigurationFor(requirement, testCRDClean)
			manualMWC.OwnerReferences = []metav1.OwnerReference{fakeOwner}
			createTestObject(ctx, manualMWC, "Manual MutatingWebhookConfiguration")
		}, defaultNodeTimeout)

		It("Should return error when validating webhook is owned by different resource", func(ctx context.Context) {
			By("Creating the CompatibilityRequirement")
			createTestObject(ctx, requirement, "CompatibilityRequirement")

			By("Verifying status reflects the ownership conflict terminal error")
			Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(SatisfyAll(
				HaveField("Status.Conditions", ContainElement(SatisfyAll(
					HaveField("Type", Equal(apiextensionsv1alpha1.CompatibilityRequirementProgressing)),
					HaveField("Status", Equal(metav1.ConditionFalse)),
					HaveField("Reason", Equal("OwnershipConflict")),
					HaveField("Message", ContainSubstring("webhook config is not controlled by CompatibilityRequirement")),
					HaveField("ObservedGeneration", Equal(requirement.Generation)),
				))),
				HaveField("Status.Conditions", ContainElement(SatisfyAll(
					HaveField("Type", Equal(apiextensionsv1alpha1.CompatibilityRequirementAdmitted)),
					HaveField("Status", Equal(metav1.ConditionTrue)),
					HaveField("ObservedGeneration", Equal(requirement.Generation)),
				))),
			))

			By("Verifying webhook remains unchanged with original owner")

			vwc := &admissionregistrationv1.ValidatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{Name: manualVWC.Name},
			}
			Expect(kWithCtx(ctx).Object(vwc)()).To(
				HaveField("ObjectMeta.OwnerReferences", ContainElement(SatisfyAll(
					HaveField("Name", Equal("different-owner")),
					HaveField("UID", Equal(types.UID("fake-uid-12345"))),
				))),
			)
		}, defaultNodeTimeout)

		It("Should return error when mutating webhook is owned by different resource", func(ctx context.Context) {
			By("Creating the CompatibilityRequirement")
			createTestObject(ctx, requirement, "CompatibilityRequirement")

			By("Verifying status reflects the ownership conflict terminal error")
			Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(
				HaveField("Status.Conditions", ContainElement(SatisfyAll(
					HaveField("Type", Equal(apiextensionsv1alpha1.CompatibilityRequirementProgressing)),
					HaveField("Status", Equal(metav1.ConditionFalse)),
					HaveField("Reason", Equal("OwnershipConflict")),
					HaveField("ObservedGeneration", Equal(requirement.Generation)),
				))),
			)

			By("Verifying mutating webhook remains unchanged with original owner")

			mwc := &admissionregistrationv1.MutatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{Name: manualMWC.Name},
			}
			Expect(kWithCtx(ctx).Object(mwc)()).To(
				HaveField("ObjectMeta.OwnerReferences", ContainElement(SatisfyAll(
					HaveField("Name", Equal("different-owner")),
					HaveField("UID", Equal(types.UID("fake-uid-12345"))),
				))),
			)
		}, defaultNodeTimeout)
	})

	Context("When deleting a CompatibilityRequirement that doesn't own webhooks", func() {
		var (
			requirement *apiextensionsv1alpha1.CompatibilityRequirement
			manualVWC   *admissionregistrationv1.ValidatingWebhookConfiguration
			manualMWC   *admissionregistrationv1.MutatingWebhookConfiguration
		)

		BeforeEach(func(ctx context.Context) {
			testCRDWorking = testCRDClean.DeepCopy()
			createTestObject(ctx, testCRDWorking, "CRD")

			// Create a requirement with a fixed name for testing
			requirement = test.GenerateTestCompatibilityRequirement(testCRDClean)
			requirement.Name = "test-requirement-no-owner"
			requirement.GenerateName = ""
			requirement.Spec.ObjectSchemaValidation.Action = apiextensionsv1alpha1.CRDAdmitActionDeny

			// Create webhook configurations WITHOUT owner references using factory functions
			manualVWC = objectvalidation.ValidatingWebhookConfigurationFor(requirement, testCRDClean)
			manualVWC.OwnerReferences = nil // No owner
			createTestObject(ctx, manualVWC, "Manual ValidatingWebhookConfiguration")

			manualMWC = objectpruning.MutatingWebhookConfigurationFor(requirement, testCRDClean)
			manualMWC.OwnerReferences = nil
			createTestObject(ctx, manualMWC, "Manual MutatingWebhookConfiguration")

			// Create requirement - it will see webhooks exist but can't own them
			createTestObject(ctx, requirement, "CompatibilityRequirement")
		}, defaultNodeTimeout)

		It("Should not delete validating webhook without owner reference", func(ctx context.Context) {
			By("Deleting the CompatibilityRequirement")
			Expect(cl.Delete(ctx, requirement)).To(Succeed())

			By("Verifying the CompatibilityRequirement is deleted")
			Eventually(kWithCtx(ctx).Get(requirement)).WithContext(ctx).Should(test.BeK8SNotFound())

			By("Verifying the validating webhook still exists")

			vwc := &admissionregistrationv1.ValidatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{Name: manualVWC.Name},
			}
			Expect(kWithCtx(ctx).Object(vwc)()).To(
				HaveField("ObjectMeta.UID", Equal(manualVWC.UID)),
			)
		}, defaultNodeTimeout)

		It("Should not delete mutating webhook without owner reference", func(ctx context.Context) {
			By("Deleting the CompatibilityRequirement")
			Expect(cl.Delete(ctx, requirement)).To(Succeed())

			By("Verifying the CompatibilityRequirement is deleted")
			Eventually(kWithCtx(ctx).Get(requirement)).WithContext(ctx).Should(test.BeK8SNotFound())

			By("Verifying the mutating webhook still exists")

			mwc := &admissionregistrationv1.MutatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{Name: manualMWC.Name},
			}
			Expect(kWithCtx(ctx).Object(mwc)()).To(
				HaveField("ObjectMeta.UID", Equal(manualMWC.UID)),
			)
		}, defaultNodeTimeout)
	})

	Context("When deleting a CompatibilityRequirement with ownership conflict", func() {
		var (
			requirement *apiextensionsv1alpha1.CompatibilityRequirement
			conflictVWC *admissionregistrationv1.ValidatingWebhookConfiguration
		)

		BeforeEach(func(ctx context.Context) {
			testCRDWorking = testCRDClean.DeepCopy()
			createTestObject(ctx, testCRDWorking, "CRD")

			requirement = test.GenerateTestCompatibilityRequirement(testCRDClean)
			requirement.Name = "requirement-with-conflict"
			requirement.GenerateName = ""
			requirement.Spec.ObjectSchemaValidation.Action = apiextensionsv1alpha1.CRDAdmitActionDeny

			// Create webhooks with the requirement's name but owned by a different requirement
			conflictVWC = objectvalidation.ValidatingWebhookConfigurationFor(requirement, testCRDClean)
			conflictVWC.OwnerReferences = []metav1.OwnerReference{{
				APIVersion: "apiextensions.openshift.io/v1alpha1",
				Kind:       "CompatibilityRequirement",
				Name:       "different-owner",
				UID:        types.UID("different-uid"),
				Controller: ptr.To(true),
			}}
			createTestObject(ctx, conflictVWC, "Conflicting ValidatingWebhookConfiguration")

			createTestObject(ctx, requirement, "CompatibilityRequirement")

			By("Waiting for the requirement to detect ownership conflict")
			Eventually(kWithCtx(ctx).Object(requirement)).WithContext(ctx).Should(
				HaveField("Status.Conditions", ContainElement(SatisfyAll(
					HaveField("Type", Equal(apiextensionsv1alpha1.CompatibilityRequirementProgressing)),
					HaveField("Status", Equal(metav1.ConditionFalse)),
					HaveField("Reason", Equal("OwnershipConflict")),
					HaveField("ObservedGeneration", Equal(requirement.Generation)),
				))),
			)
		}, defaultNodeTimeout)

		It("Should not delete webhook owned by different CompatibilityRequirement", func(ctx context.Context) {
			By("Deleting the CompatibilityRequirement")
			Expect(cl.Delete(ctx, requirement)).To(Succeed())

			By("Verifying the CompatibilityRequirement is deleted")
			Eventually(kWithCtx(ctx).Get(requirement)).WithContext(ctx).Should(test.BeK8SNotFound())

			By("Verifying webhook still exists with original owner reference")

			vwc := &admissionregistrationv1.ValidatingWebhookConfiguration{
				ObjectMeta: metav1.ObjectMeta{Name: conflictVWC.Name},
			}
			Expect(kWithCtx(ctx).Object(vwc)()).To(
				HaveField("ObjectMeta.OwnerReferences", ContainElement(
					HaveField("Name", Equal("different-owner")),
				)),
			)
		}, defaultNodeTimeout)
	})

	Context("When creating or modifying a CRD", func() {
		testIncompatibleCRD := func(ctx context.Context, testCRD *apiextensionsv1.CustomResourceDefinition, requirement *apiextensionsv1alpha1.CompatibilityRequirement, createOrUpdateCRD func(context.Context, client.Object, func()) func() error) {
			// Create a working copy of the CRD so we maintain a clean version
			// without runtime metadata
			testCRDWorking := testCRD.DeepCopy()

			By("Attempting to make an invalid modification by removing a field")

			expectedError := "admission webhook \"compatibilityrequirement.operator.openshift.io\" denied the request: CRD is not compatible with CompatibilityRequirements: This requirement was added by CompatibilityRequirement " + requirement.Name + ": removed field : v1.^.status"
			updateCRD := createOrUpdateCRD(ctx, testCRDWorking, func() {
				delete(testCRDWorking.Spec.Versions[0].Schema.OpenAPIV3Schema.Properties, "status")
			})
			Eventually(updateCRD).WithContext(ctx).Should(MatchError(expectedError))
		}

		testCompatibleCRD := func(ctx context.Context, testCRD *apiextensionsv1.CustomResourceDefinition, createOrUpdateCRD func(context.Context, client.Object, func()) func() error) {
			// Create a working copy of the CRD so we maintain a clean version
			// without runtime metadata
			testCRDWorking := testCRD.DeepCopy()

			By("Attempting to make a valid modification by adding a field")

			updateCRD := createOrUpdateCRD(ctx, testCRDWorking, func() {
				testCRDWorking.Spec.Versions[0].Schema.OpenAPIV3Schema.Properties["foo"] = apiextensionsv1.JSONSchemaProps{
					Type: "string",
				}
			})
			Eventually(updateCRD).WithContext(ctx).Should(Succeed(), "The test CRD should be modified")
		}

		Context("When modifying a CRD with a requirement", func() {
			var (
				requirement *apiextensionsv1alpha1.CompatibilityRequirement
			)

			BeforeEach(func(ctx context.Context) {
				createTestObject(ctx, testCRDClean.DeepCopy(), "CRD")

				requirement = test.GenerateTestCompatibilityRequirement(testCRDClean)
				createTestObject(ctx, requirement, "CompatibilityRequirement")
				waitForAdmitted(ctx, requirement)
			}, defaultNodeTimeout)

			It("Should not permit a CRD with requirements to be deleted", func(ctx context.Context) {
				By("Attempting to delete CRD " + testCRDClean.Name)
				Eventually(tryDelete(ctx, testCRDClean)).WithContext(ctx).Should(MatchError(ContainSubstring(crdvalidation.ErrCRDHasRequirements.Error())), "The test CRD should not be deleted")
			}, defaultNodeTimeout)

			updateCRD := func(ctx context.Context, obj client.Object, updateFn func()) func() error {
				return kWithCtx(ctx).Update(obj, updateFn)
			}

			It("Should not permit an incompatible CRD modification", func(ctx context.Context) {
				testIncompatibleCRD(ctx, testCRDClean, requirement, updateCRD)
			}, defaultNodeTimeout)

			It("Should permit a compatible CRD modification", func(ctx context.Context) {
				testCompatibleCRD(ctx, testCRDClean, updateCRD)
			}, defaultNodeTimeout)
		})

		Context("When creating a CRD with a requirement", func() {
			var (
				requirement *apiextensionsv1alpha1.CompatibilityRequirement
			)

			BeforeEach(func(ctx context.Context) {
				testCRDWorking = test.GenerateTestCRD()

				// We need to register this before the requirement is created so
				// it will be deleted after the requirement is deleted
				deferCleanupTestObject(testCRDWorking, "CRD")

				requirement = test.GenerateTestCompatibilityRequirement(testCRDWorking)
				createTestObject(ctx, requirement, "CompatibilityRequirement")
				waitForAdmitted(ctx, requirement)
			}, defaultNodeTimeout)

			createCRD := func(ctx context.Context, obj client.Object, updateFn func()) func() error {
				return func() error {
					By("Creating test CRD " + obj.GetName())

					updateFn()

					return cl.Create(ctx, obj)
				}
			}

			It("Should not permit an incompatible CRD to be created", func(ctx context.Context) {
				testIncompatibleCRD(ctx, testCRDWorking, requirement, createCRD)
			}, defaultNodeTimeout)

			It("Should permit a compatible CRD to be created", func(ctx context.Context) {
				testCompatibleCRD(ctx, testCRDWorking, createCRD)
			}, defaultNodeTimeout)
		})

		Context("When creating a CRD with a requirement which has no CustomResourceDefinitionSchemaValidation", func() {
			var (
				requirement *apiextensionsv1alpha1.CompatibilityRequirement
			)

			BeforeEach(func(ctx context.Context) {
				testCRDWorking = test.GenerateTestCRD()
				deferCleanupTestObject(testCRDWorking, "CRD")

				requirement = test.GenerateTestCompatibilityRequirement(testCRDWorking)
				requirement.Spec.CustomResourceDefinitionSchemaValidation = (apiextensionsv1alpha1.CustomResourceDefinitionSchemaValidation{})

				createTestObject(ctx, requirement, "CompatibilityRequirement")
				waitForAdmitted(ctx, requirement)
			}, defaultNodeTimeout)

			createCRD := func(ctx context.Context, obj client.Object, updateFn func()) func() error {
				return func() error {
					By("Creating test CRD " + obj.GetName())

					updateFn()

					return cl.Create(ctx, obj)
				}
			}

			It("Should permit a compatible CRD to be created", func(ctx context.Context) {
				testCompatibleCRD(ctx, testCRDWorking, createCRD)
			}, defaultNodeTimeout)

			It("Should permit an incompatible CRD to be created", func(ctx context.Context) {
				updateCRD := createCRD(ctx, testCRDWorking, func() {
					delete(testCRDWorking.Spec.Versions[0].Schema.OpenAPIV3Schema.Properties, "status")
				})
				Eventually(updateCRD).WithContext(ctx).Should(Succeed(), "The test CRD should be modified")
			}, defaultNodeTimeout)
		})
	})
})
