apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-cluster-api

patches:

# Retain Secrets internally for reference tracking, but don't emit them
- target:
    kind: Secret
  patch: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: __ignored__
      annotations:
        config.kubernetes.io/local-config: "true"

# Set the required SCC annotation on all Deployments' pod templates.
# Default to the most restrictive SCC, this can be overridden by the providers upon manifest generation.
# See: https://github.com/openshift/enhancements/blob/master/enhancements/authentication/custom-scc-preemption-prevention.md
- target:
    kind: Deployment
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: __ignored__
    spec:
      template:
        metadata:
          annotations:
            openshift.io/required-scc: "restricted-v2"
